# Generated by Django 4.2.6 on 2023-12-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='genre',
            table='Genres',
        ),
        migrations.AlterModelTable(
            name='users',
            table='Users',
        ),
    ]
