# Generated by Django 4.2.6 on 2023-12-11 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_genre_table_alter_users_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genre',
            options={'verbose_name': 'Genre', 'verbose_name_plural': 'Genres'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
