# Generated by Django 4.2.6 on 2024-02-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_alter_genre_genre_alter_users_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consommateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_association', models.CharField(blank=True, max_length=250, null=True)),
                ('localisation', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('site_internet', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Consommateur',
                'verbose_name_plural': 'Consommateurs',
                'db_table': 'Consommateur',
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_etablissement', models.CharField(blank=True, max_length=250, null=True)),
                ('zone_intervention', models.CharField(blank=True, max_length=250, null=True)),
                ('localisation', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('site_internet', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
                'db_table': 'Etablissement',
            },
        ),
        migrations.CreateModel(
            name='Importateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_distributeur', models.CharField(blank=True, max_length=250, null=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('zone_importation', models.CharField(blank=True, max_length=250, null=True)),
                ('localisation', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('site_internet', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Importateur',
                'verbose_name_plural': 'Importateurs',
                'db_table': 'Importateur',
            },
        ),
        migrations.CreateModel(
            name='Producteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_op', models.CharField(blank=True, max_length=250, null=True)),
                ('producteur_paddy_semences', models.CharField(blank=True, max_length=250, null=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('superficie', models.IntegerField(blank=True, null=True)),
                ('localisation', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('site_internet', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Producteur',
                'verbose_name_plural': 'Producteurs',
                'db_table': 'Producteur',
            },
        ),
        migrations.CreateModel(
            name='Tranformateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_transformateur', models.CharField(blank=True, max_length=250, null=True)),
                ('capacite', models.IntegerField(blank=True, null=True)),
                ('zone_de_transformation', models.CharField(blank=True, max_length=250, null=True)),
                ('localisation', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('site_internet', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Tranformateur',
                'verbose_name_plural': 'Tranformateurs',
                'db_table': 'Tranformateur',
            },
        ),
        migrations.CreateModel(
            name='Vendeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_vendeur', models.CharField(blank=True, max_length=250, null=True)),
                ('type_intrants', models.CharField(blank=True, max_length=250, null=True)),
                ('zone_intervention', models.CharField(blank=True, max_length=250, null=True)),
                ('localisation', models.CharField(blank=True, max_length=250, null=True)),
                ('contact', models.IntegerField(blank=True, null=True)),
                ('site_internet', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Vendeur',
                'verbose_name_plural': 'Vendeurs',
                'db_table': 'Vendeur',
            },
        ),
    ]
