# Generated by Django 4.2.6 on 2024-02-04 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_consommateur_etablissement_importateur_producteur_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffreDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('population', models.IntegerField()),
                ('consommateur', models.IntegerField()),
                ('consommateur_par_tete', models.IntegerField()),
                ('demande_totale', models.IntegerField()),
                ('offre', models.IntegerField()),
                ('gap', models.IntegerField()),
            ],
            options={
                'verbose_name': 'OffreDemande',
                'verbose_name_plural': 'OffreDemandes',
                'db_table': 'OffreDemande',
            },
        ),
    ]
