# Generated by Django 4.2.6 on 2024-02-04 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_offredemande'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offredemande',
            old_name='demande_totale',
            new_name='demande_total',
        ),
    ]
