# Generated by Django 4.2.6 on 2024-02-04 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_offredemande_annee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offredemande',
            name='consommateur_par_tete',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
