# Generated by Django 4.2.6 on 2024-02-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_alter_offredemande_consommateur_par_tete'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActeurEtPotentiel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('superficie_exploite', models.IntegerField(blank=True, null=True)),
                ('superficie_potentielle', models.IntegerField(blank=True, null=True)),
                ('production_actuelle', models.IntegerField(blank=True, null=True)),
                ('production_potentielle', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ActeurEtPotentiel',
                'verbose_name_plural': 'ActeurEtPotentiels',
                'db_table': 'ActeurEtPotentiel',
            },
        ),
    ]
