# Generated by Django 4.2.6 on 2024-02-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_acteuretpotentiel'),
    ]

    operations = [
        migrations.AddField(
            model_name='acteuretpotentiel',
            name='acteur',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
