# Generated by Django 4.2.6 on 2024-02-05 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_acteuretpotentiel_acteur'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_bibliotheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Documents_bibliotheque',
                'verbose_name_plural': 'Documents_bibliotheque',
                'db_table': 'Documents_bibliotheque',
            },
        ),
        migrations.CreateModel(
            name='Documents_sir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Documents_sir',
                'verbose_name_plural': 'Documents_sir',
                'db_table': 'Documents_sir',
            },
        ),
    ]
