# Generated by Django 4.2.6 on 2024-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_documents_bibliotheque_documents_sir'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents_bibliotheque',
            name='document',
            field=models.FileField(upload_to='docs/'),
        ),
        migrations.AlterField(
            model_name='documents_sir',
            name='document',
            field=models.FileField(upload_to='docs/'),
        ),
    ]
