# Generated by Django 4.2.6 on 2024-02-05 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_documents_bibliotheque_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents_bibliotheque',
            name='document',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='documents_sir',
            name='document',
            field=models.FileField(upload_to=''),
        ),
    ]
