# Generated by Django 4.2.6 on 2024-02-07 07:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_documents_bibliotheque_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documents_bibliotheque',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documents_sir',
            name='document',
        ),
        migrations.AddField(
            model_name='documents_bibliotheque',
            name='fichier',
            field=models.FileField(default=12, upload_to='staticfiles/documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents_bibliotheque',
            name='nom',
            field=models.CharField(default=12, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents_sir',
            name='fichier',
            field=models.FileField(default=django.utils.timezone.now, upload_to='staticfiles/documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documents_sir',
            name='nom',
            field=models.CharField(default=django.utils.timezone.now, max_length=250),
            preserve_default=False,
        ),
    ]
