# Generated by Django 4.2.6 on 2024-02-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_remove_documents_bibliotheque_document_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents_Hand_in_Hand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('fichier', models.FileField(upload_to='staticfiles/documents')),
            ],
            options={
                'verbose_name': 'Documents_Hand_in_Hand',
                'verbose_name_plural': 'Documents_Hand_in_Hand',
                'db_table': 'Documents_Hand_in_Hand',
            },
        ),
    ]
