# Generated by Django 4.2.6 on 2024-02-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0020_images_mediatheque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Liens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('url', models.URLField()),
            ],
            options={
                'verbose_name': 'Liens',
                'verbose_name_plural': 'Liens',
                'db_table': 'Liens',
            },
        ),
    ]
