# Generated by Django 4.2.6 on 2024-02-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0021_liens'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvolutionRiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('sud', models.IntegerField(blank=True, null=True)),
                ('centre', models.IntegerField(blank=True, null=True)),
                ('est', models.IntegerField(blank=True, null=True)),
                ('ouest', models.IntegerField(blank=True, null=True)),
                ('littoral', models.IntegerField(blank=True, null=True)),
                ('sud_ouest', models.IntegerField(blank=True, null=True)),
                ('nord_ouest', models.IntegerField(blank=True, null=True)),
                ('adamaoua', models.IntegerField(blank=True, null=True)),
                ('nord', models.IntegerField(blank=True, null=True)),
                ('extreme_nord', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Evolution_Riz',
                'verbose_name_plural': 'Evolution_Riz',
                'db_table': 'Evolution_Riz',
            },
        ),
    ]
